version: "3.0"
services:
  backend:
    image: docker.1ms.run/elabosak233/cdsctf:latest
    ports:
      - "80:8888"
    restart: always
    volumes:
      - "backend:/app/data"
      - "./configs:/etc/cdsctf"
    depends_on:
      - db
      - queue
      - cache
    networks:
      cdsnet:
        ipv4_address: "172.20.0.10"

  db:
    image: docker.1ms.run/postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: cdsctf
      POSTGRES_PASSWORD: cdsctf
      POSTGRES_DB: cdsctf
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      cdsnet:

  queue:
    image: docker.1ms.run/nats:alpine
    restart: always
    command:
      - "--js"
      - "--sd=/data"
    volumes:
      - "queue:/data"
    networks:
      cdsnet:

  cache:
    image: docker.1ms.run/valkey/valkey:alpine
    restart: always
    volumes:
      - "cache:/data"
    networks:
      cdsnet:

  #telemetry:
  #  image: docker.1ms.run/otel/opentelemetry-collector:latest
  #  ports:
  #    - "127.0.0.1:2345:2345"
  #  volumes:
  #    - "./otel-config.yml:/otel-config.yml:ro"
  #  command: ["--config", "/otel-config.yml"]
  #  restart: unless-stopped
  #  networks:
  #    cdsnet:

volumes:
  backend:
  db:
  queue:
  cache:

networks:
  cdsnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
