services:
  server:
    image: docker.1ms.run/elabosak233/cdsctf:latest
    ports:
      - "80:8888"
    restart: always
    environment:
      - KUBECONFIG=/etc/cdsctf/k8s.yml
    volumes:
      - "./configs:/etc/cdsctf"
    depends_on:
      - db
      - queue
      - cache
      - media
    networks:
      cdsnet:
        ipv4_address: "172.20.0.10"

  db:
    image: docker.1ms.run/library/postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: cdsctf
      POSTGRES_PASSWORD: cdsctf
      POSTGRES_DB: cdsctf
    volumes:
      - "db:/var/lib/postgresql"
    networks:
      cdsnet:

  queue:
    image: docker.1ms.run/library/nats:2-alpine
    restart: always
    command:
      - "--js"
      - "--sd=/data"
    volumes:
      - "queue:/data"
    networks:
      cdsnet:

  cache:
    image: docker.1ms.run/valkey/valkey:9-alpine
    restart: always
    volumes:
      - "cache:/data"
    networks:
      cdsnet:

  media:
    image: docker.1ms.run/rustfs/rustfs:latest
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: cdsctf
      RUSTFS_SECRET_KEY: cdsctf
    volumes:
      - media:/data
    networks:
      cdsnet:

volumes:
  db:
  queue:
  cache:
  media:

networks:
  cdsnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
